// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public int ComponentId { get; set; }

    public string Name { get; set; }

    public virtual Component Component { get; set; }
}