// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class Component
{
    public int ComponentId { get; set; }

    public int MaterialId { get; set; }

    public int ColorId { get; set; }

    public int StatusId { get; set; }

    public string Name { get; set; }

    public string Category { get; set; }

    public decimal OriginalPrice { get; set; }

    public string FbxfileName { get; set; }

    public string ImageFileName { get; set; }

    public bool IsCustomized { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual Color Color { get; set; }

    public virtual ICollection<CustomizedSpecification> CustomizedSpecifications { get; set; } = new List<CustomizedSpecification>();

    public virtual ICollection<InspirationSpecification> InspirationSpecifications { get; set; } = new List<InspirationSpecification>();

    public virtual Material Material { get; set; }

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; } = new List<ProductSpecification>();

    public virtual Status Status { get; set; }
}