// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class ImageCarousel
{
    public int ImageCarouselId { get; set; }

    public string Image { get; set; }

    public string Description { get; set; }
}