// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class Material
{
    public int MaterialId { get; set; }

    public string Name { get; set; }

    public string ImageFileName { get; set; }

    public virtual ICollection<Component> Components { get; set; } = new List<Component>();

    public virtual ICollection<CustomizedSpecification> CustomizedSpecifications { get; set; } = new List<CustomizedSpecification>();

    public virtual ICollection<InspirationSpecification> InspirationSpecifications { get; set; } = new List<InspirationSpecification>();

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; } = new List<ProductSpecification>();
}