// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class MemberActivitylog
{
    public int ActivitylogId { get; set; }

    public int MemberId { get; set; }

    public DateTime? LoginTime { get; set; }

    public virtual Member Member { get; set; }
}