// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class MemberLevel
{
    public int LevelId { get; set; }

    public string Name { get; set; }

    public int Level { get; set; }

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();
}