// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public int PaymentStatusId { get; set; }

    public int PaymentId { get; set; }

    public int? PromoCodeId { get; set; }

    public int ShippingId { get; set; }

    public string RecipientName { get; set; }

    public string RecipientAddress { get; set; }

    public string BillRecipientName { get; set; }

    public string BillRecipientAddress { get; set; }

    public int ShippingStatusId { get; set; }

    public DateTime CreationTime { get; set; }

    public DateTime? CompletionTime { get; set; }

    public int OrderStatusId { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual OrderStatus OrderStatus { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }

    public virtual PromoCode PromoCode { get; set; }

    public virtual Shipping Shipping { get; set; }

    public virtual ShippingStatus ShippingStatus { get; set; }
}