// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class PasswordReset
{
    public int TokenId { get; set; }

    public int UserId { get; set; }

    public string Token { get; set; }

    public DateTime ExpiryDate { get; set; }
}