// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int PromotionId { get; set; }

    public int StatusId { get; set; }

    public string Name { get; set; }

    public string Category { get; set; }

    public string ImageFileName { get; set; }

    public decimal OriginalPrice { get; set; }

    public decimal SalePrice { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<FavoriteItem> FavoriteItems { get; set; } = new List<FavoriteItem>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; } = new List<ProductSpecification>();

    public virtual Promotion Promotion { get; set; }

    public virtual Status Status { get; set; }
}