// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace modpackApi.Models;

public partial class StoreLocation
{
    public int StoreLocationId { get; set; }

    public string Name { get; set; }

    public string OfficeTelephone { get; set; }

    public string Address { get; set; }
}